services:
  kreuzberg:
    build:
      context: .
      dockerfile: Dockerfile
      target: install
    ports:
      - "8000:8000"
    volumes:
      - ./kreuzberg:/src/kreuzberg:cached
      - ./tests:/src/tests:cached
